In [1]:
import pandas as pd
import numpy as np
import gc

In [2]:
print(f"Pandas version is: {pd.__version__}")

Pandas version is: 2.0.3


In [3]:
URL = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"

In [4]:
data = pd.read_csv(URL)
print(f" Shape of the data (columns, rows) : {data.shape}")

 Shape of the data (columns, rows) : (20640, 10)


In [5]:
print(f"Missing values:\n{data.isna().sum()}")

Missing values:
longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64


In [6]:
print(f"Number of uniques values in 'ocean_proximity': {data['ocean_proximity'].nunique()};\nValues in ocean_proximity: {data['ocean_proximity'].unique()}")

Number of uniques values in 'ocean_proximity': 5;
Values in ocean_proximity: ['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']


In [16]:
average_value = data["median_house_value"][data["ocean_proximity"] == 'NEAR BAY'].mean()
print(f"Average value of 'median_house_value': {round(average_value, 3)}")

Average value of 'median_house_value': 259212.312


In [8]:
df = data.copy()
df.fillna(259212)

average_value_without_missing_value = df["median_house_value"][df["ocean_proximity"] == 'NEAR BAY'].mean()
print(f"Average value of 'median_house_value': {round(average_value_without_missing_value, 3)}")

Average value of 'median_house_value': 259212.312


In [9]:
del df
gc.collect()

0

## Linear Regression

In [10]:
data_islands = data[data["ocean_proximity"] == "ISLAND"]
data_islands = data_islands[["housing_median_age", "total_rooms", "total_bedrooms"]]
data_islands.head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [11]:
X = np.array(data_islands)
print(X)

[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


In [12]:
XTX = np.dot(X.T, X)
print(XTX)

[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


In [13]:
list_for_y = [950, 1300, 800, 1000, 1300]

In [14]:
y = np.array(list_for_y)
print(y)

[ 950 1300  800 1000 1300]


In [15]:
w = np.dot(np.dot(np.linalg.inv(XTX), X.T), y)
print(w)

[23.12330961 -1.48124183  5.69922946]
