In [1]:
import pandas as pd
import numpy as np
import gc

*1) What's the version of Pandas that you installed?*

In [2]:
print(f"Pandas version is: {pd.__version__}")

Pandas version is: 2.0.3


In [3]:
# URL where to download dataset

URL = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"

*2) How many columns are in the dataset?*

In [4]:
data = pd.read_csv(URL)
print(f" Shape of the data (columns, rows): {data.shape}")

 Shape of the data (columns, rows): (20640, 10)


*3) Which columns in the dataset have missing values?*

In [5]:
print(f"Missing values:\n{data.isna().sum()}")

Missing values:
longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64


*4) How many unique values does the `ocean_proximity` column have?*

In [6]:
print(f"Number of uniques values in 'ocean_proximity': {data['ocean_proximity'].nunique()};\nValues in ocean_proximity: {data['ocean_proximity'].unique()}")

Number of uniques values in 'ocean_proximity': 5;
Values in ocean_proximity: ['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']


*5) What's the average value of the `median_house_value` for the houses located near the bay?*

In [7]:
average_value = data["median_house_value"][data["ocean_proximity"] == 'NEAR BAY'].mean()
print(f"Average value of 'median_house_value': {round(average_value, 3)}")

Average value of 'median_house_value': 259212.312


*Question 6:*

1. Calculate the average of `total_bedrooms` column in the dataset.
2. Use the fillna method to fill the missing values in `total_bedrooms` with the mean value from the previous step.
3. Now, calculate the average of `total_bedrooms` again.
4. Has it changed?


In [8]:
average_total_bedrooms = data['total_bedrooms'].mean()
print(f"Average total bedrooms: {average_total_bedrooms}")

Average total bedrooms: 537.8705525375618


In [9]:
df = data.copy()
df.fillna(average_total_bedrooms)

average_total_bedrooms_without_na = df["total_bedrooms"].mean()
print(f"Average total bedrooms without na: {round(average_total_bedrooms_without_na, 3)}")

Average total bedrooms without na: 537.871


In [10]:
del df
gc.collect()

0

*Question 7:*

1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.

In [11]:
data_islands = data[data["ocean_proximity"] == "ISLAND"]
data_islands = data_islands[["housing_median_age", "total_rooms", "total_bedrooms"]]
data_islands.head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

3. Get the underlying NumPy array. Let's call it X.

In [12]:
X = np.array(data_islands)
print(X)

[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [13]:
XTX = np.dot(X.T, X)
print(XTX)

[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


5. Compute the inverse of XTX.

In [14]:
inv_XTX = np.linalg.inv(XTX)

6. Create an array y with values [950, 1300, 800, 1000, 1300].

In [15]:
list_for_y = [950, 1300, 800, 1000, 1300]

In [16]:
y = np.array(list_for_y)
print(y)

[ 950 1300  800 1000 1300]


7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [17]:
w = np.dot(np.dot(np.linalg.inv(XTX), X.T), y)
print(w)

[23.12330961 -1.48124183  5.69922946]


8. What's the value of the last element of w?

In [18]:
print(f"The last element of w is: {w[-1]}")

The last element of w is: 5.699229455065586
