# Machine Learning Zoomcamp

**Plan :**
- Creating arrays
- Multidimensional arrays
- Randomly generated arrays
- Element-wise operations
- Summarizing operations

In [2]:
import numpy as np

## 1) Création d'array

In [3]:
# création d'un array avec des zéros. On spécifie la taille.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# création d'un array avec des uns. On spécifie la taille.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
# Création d'un array dans lequel on spécifie la taille et ensuite la valeur.
np.full(5, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
# Création d'un array à partir d'une liste

my_list = [1, 2, 3, 4, 5]
a = np.array(my_list)
a

array([1, 2, 3, 4, 5])

In [9]:
# Accéder à un élément d'un array
a[2]

3

In [10]:
# Modifier une valeur dans un array
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [11]:
# Créer un array avec un intervalle de valeurs
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
# Création d'un array dans un espace défini avec un nombre de valeur défini
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## 2) Array multidimensionnel

In [16]:
# Création d'un array avec 5 lignes et 2 colonnes
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# Accéder à une valeur (indice de la ligne et indice de la colonne)
n[0, 1]

2

In [21]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [19]:
# Accéder à une colonne
n[2]

array([7, 8, 9])

In [22]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [23]:
n[:, 1]

array([20,  5,  1])

## 3) Génération aléatoire d'arrays

In [24]:
# Création d'un array avec un génération aléatoire
# Il est possible de fixer la seed de génération aléatoire pour rendre cela reproductible. 
np.random.seed = 42
np.random.rand(5, 2)

array([[0.48619266, 0.3434786 ],
       [0.36305866, 0.84330041],
       [0.83401275, 0.35182821],
       [0.5983976 , 0.05185654],
       [0.94191804, 0.92470274]])

In [25]:
# Génération d'un array de manière aléatoire et suivant la loi normale
np.random.seed = 42
np.random.randn(5, 2)

array([[ 0.73185534,  1.06692508],
       [-0.85798387, -2.13796392],
       [-0.23422185, -0.02453574],
       [-0.63554573,  1.04455044],
       [ 0.3391635 ,  2.03144918]])

In [26]:
np.random.seed = 42
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 22],
       [68, 44],
       [82, 96],
       [ 4, 91],
       [38, 80]])

## 4) Element-wise operations

In [27]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
a + 1

array([1, 2, 3, 4, 5])

In [29]:
a * 2

array([0, 2, 4, 6, 8])

In [32]:
b = (10 + (a * 2)) ** 2 / 100

In [35]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

### Comparaisons

In [36]:
a

array([0, 1, 2, 3, 4])

In [37]:
a >= 2

array([False, False,  True,  True,  True])

In [38]:
a > b

array([False, False,  True,  True,  True])

In [39]:
a[a > b]

array([2, 3, 4])

## 5) Summarizing operations

In [40]:
a

array([0, 1, 2, 3, 4])

In [41]:
a.min()

0

In [42]:
a.max()

4

In [43]:
a.sum()

10

In [44]:
a.mean()

2.0

In [46]:
a.std()

1.4142135623730951

In [47]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [48]:
n.sum()

42

In [49]:
n.min()

1

In [50]:
n.max()

20